#include"Runtime.h"
#include<Drivers/Screen.h>
#include<Mego-Runtime/Runtime.h>
#include<Drivers/Keyboard.h>
#include<Timer/Timer.h>
void execute_command(int command){
  if(command==1){
    printC(getRegValueOf(3));
  }
  if(command==2){
     setRegValueOf(4,readChar());
  }
  if(command==3){
    clearScreen();
  }
  if(command==4){
    setDefaultColor(0x10+getRegValueOf(6));
  }
  if(command==5){
    Sleep(getRegValueOf(3));
  }
}